name: Create developmento build

on:
  push:
    braches:
      - "develop"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PKG_NODE_VERSION: 16
      NODE_VERSION: 16
      HAXE_VERSION: latest
      JS_VERSION_NAME: ideckia-js
      PKG_ARGS: --no-bytecode --public --public-packages '*' --compress Brotli --debug

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install lix, haxe ${{ env.HAXE_VERSION }} and dependencies
      run: |
        npm install
        npm i -g lix
        lix install haxe ${{ env.HAXE_VERSION }}
        lix download

    - name: Compile server
      run: haxe deploy_server.hxml

    - name: Compile editor
      run: haxe deploy_editor.hxml

    - name: Install node.js dependencies
      run: npm install

    - name: Get tray windows executable
      uses: robinraju/release-downloader@v1
      with:
        repository: "ideckia/tray"
        latest: true
        tarBall: false
        zipBall: false
        fileName: "ideckia_tray.exe"
        out-file-path: "bin/tray"

    - name: Get tray linux executable
      uses: robinraju/release-downloader@v1
      with:
        repository: "ideckia/tray"
        latest: true
        tarBall: false
        zipBall: false
        fileName: "ideckia_tray_linux"
        out-file-path: "bin/tray"

    - name: Get tray macos executable
      uses: robinraju/release-downloader@v1
      with:
        repository: "ideckia/tray"
        latest: true
        tarBall: false
        zipBall: false
        fileName: "ideckia_tray_macos"
        out-file-path: "bin/tray"

    - name: Install pkg
      run: npm i -g pkg@5.8.0
    
    - name: Package with pkg
      run: |
        mkdir ${{ env.JS_VERSION_NAME }}
        cp bin/ideckia.js ${{ env.JS_VERSION_NAME }}
        cp bin/editor ${{ env.JS_VERSION_NAME }}
        zip -r ${{ env.JS_VERSION_NAME }} ${{ env.JS_VERSION_NAME }}
        pkg . --targets node${{ env.PKG_NODE_VERSION }}-linux,node${{ env.PKG_NODE_VERSION }}-win,node${{ env.PKG_NODE_VERSION }}-macos ${{ env.PKG_ARGS }}

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ideckia-linux
          ideckia-macos
          ideckia-win.exe
          ${{ env.JS_VERSION_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
